#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Dec  6 16:24:54 2022

@author: jeffreymullahey
"""



# import modules

import os
import re
import sklearn
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from collections import Counter
from sklearn.metrics import *
from sklearn.linear_model import *
from sklearn.model_selection import *

pd.set_option('display.max_columns', None)


# connect to data provided by Kaggle
# I downloaded the data to my personal folder

DATA_PATH = '/Users/jeffreymullahey/Documents/GitHub/marchmadness2022/mens-march-mania-2022/MDataFiles_Stage1'

for filename in os.listdir(DATA_PATH):
    print(filename)